apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-app-deployment  # Name of the Deployment
spec:
  replicas: 1  # Number of Pod replicas
  selector:
    matchLabels:
      app: k8-app  # Label used to identify Pods
  template:
    metadata:
      labels:
        app: k8-app  # Label assigned to the Pods
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: k8-app-container  # Name of the container
        image: 774305585645.dkr.ecr.ap-south-1.amazonaws.com/project-devops:latest
        
        ports:
        - containerPort: 8000  # Port exposed by the container
        resources:
          requests:  # Minimum resources required
            memory: "128Mi"  # Minimum memory (128 MiB)
            cpu: "250m"      # Minimum CPU (0.25 cores)
          limits:  # Maximum resources allowed
            memory: "512Mi"  # Maximum memory (512 MiB)
            cpu: "500m"      # Maximum CPU (0.5 cores)
